# Generated by Django 6.0.5 on 2026-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeeid', models.IntegerField()),
                ('Employeename', models.CharField(max_length=30)),
                ('Employeesalary', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
